[package]
name = "mkdsk"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
is-url = "1.0.4"
path-absolutize = "3.1.1"
